#
# name that will be displayed in the Filter header. This property is mandatory
#
FILTER_DISPLAYNAME=Jabber Filter Configuration
#
# Description that will be displayed in the filter header. This property is mandatory
#
FILTER_DESCRIPTION=Configure parameter values for the Jabber Filter

#
# Properties for the JabberFilter Configuration Wizard
#
#
# Field labels and descriptions
#
CONNECTION_SETTINGS_LABEL=Connection Settings
FROM_EMAIL_ADDRESS_LABEL=From :
FROM_EMAIL_ADDRESS_DISP_NAME=Person sending the instant message
FROM_PASSWORD_LABEL=Password :
FROM_PASSWORD_DISP_NAME=Password of Person sending the message
RESOURCE_NAME_LABEL=Resource Name:
RESOURCE_NAME_DISP_NAME=Unique resource Name
CHAT_SETTINGS_LABEL=Chat Settings
TO_EMAIL_ADDRESS_LABEL=To :
TO_EMAIL_ADDRESS_DISP_NAME=Person receiving the instant message
MESSAGE_LABEL=Message :
MESSAGE_DISP_NAME=Message Content
